version: '3.8'

services:
  go-server-8080:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ZOOKEEPER_SERVERS=zookeeper:2181
    depends_on:
      - zookeeper
  go-server-8081:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - ZOOKEEPER_SERVERS=zookeeper:2181
    depends_on:
      - zookeeper
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
